### ISSUE TITLE
Can you share the schematic

### ISSUE THREAD

**Issue by greenscreenflicker** [suzan-works/USBPDTrigger-VoltDisplay#1]
@suzan-works can you please share the kicad schematic?

**Comment by suzan-works** [comment]
[the schematic](https://github.com/suzan-works/USBPDTrigger-VoltDisplay/blob/main/KiCad/CH32X035_USBPD-Trigger_4.kicad_sch) is already available.

**Comment by suzan-works** [comment]
You can view the schematic in your browser [here](https://kicanvas.org/?github=https%3A%2F%2Fgithub.com%2Fsuzan-works%2FUSBPDTrigger-VoltDisplay%2Fblob%2Fmain%2FKiCad%2FCH32X035_USBPD-Trigger_4.kicad_sch).

**Comment by greenscreenflicker** [comment]
@suzan-works thank you, didn't see it!
